Generate test application automatically
monsieurbiz/SyliusCmsPagePlugin pull request #35
Opened 2021-10-30 15:38 UTC by maximehuran

2021-12-22 13:58 UTC, jacquesbh requested changes

2021-12-22 13:58 UTC, jacquesbh commented on .github/workflows/recipe.yaml
> +
@maximehuran Isn't it blocking the cache if this `mkdir` is done before next step?

Isn't it better to keep it after?

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +dependencies: composer.lock node_modules ## Setup the dependencies
If we have a composer.lock but no vendor/ directory then nothing will happen…

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +	ln -s .php-version.dist .php-version
Please copy, do not use a symlink.

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +	ln -s php.ini.dist php.ini
Same here, could you use a copy and not a symlink please?>

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +	$(MAKE) ${APP_DIR}/php.ini
```suggestion
	$(MAKE) apply_dist ${APP_DIR}/.php-version ${APP_DIR}/php.ini
```

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +	ln -s ../../docker-compose.yaml.dist ${APP_DIR}/docker-compose.yaml
Same, a copy is fine.

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +	(cd ${APP_DIR} && ln -sf ../../php.ini)
Copy… copy…

2021-12-22 13:58 UTC, jacquesbh commented on Makefile
> +		(cd ${APP_DIR} && ln -s $$ROOT_DIR/dist/$$FILE_PATH $$FILE_PATH); \
Symlinks are fine here.

2021-12-22 13:58 UTC, jacquesbh commented on composer.json
> -        "config-dir": "./tests/Application/config/"
Isn't this useful?

2021-12-22 13:58 UTC, jacquesbh commented on composer.json
> +        },
Is that required?

2021-12-22 13:58 UTC, jacquesbh commented on phpstan.neon
>      checkMissingIterableValueType: false
```suggestion
    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false
```

2021-12-22 13:58 UTC, jacquesbh commented on src/Context/LastChanceLocaleContext.php
> +        $request = $this->requestStack->getMasterRequest();
Hum… really?

2021-12-22 13:58 UTC, jacquesbh commented on src/Routing/RequestContext.php
> +        if ($request !== $this->requestStack->getMasterRequest()) {
Really?

2021-12-22 13:58 UTC, jacquesbh commented on symfony.lock
> -{
Did you remove this file? Don't we want to keep it?

2022-04-08 13:05 UTC, delyriand approved these changes

2022-04-08 13:05 UTC, merged