Update to 1.0 with Sylius 1.8 and Rich Editor 2.0
monsieurbiz/SyliusCmsPagePlugin pull request #4
Opened 2020-11-09 16:47 UTC by maximehuran

2020-11-09 17:58 UTC, jacquesbh requested changes

2020-11-10 06:34 UTC, maximehuran commented on src/Entity/Page.php
> +     * @ORM\Column(type="boolean", options={"default"=true})
PHP CS I think

2020-11-10 06:34 UTC, maximehuran commented on src/Entity/Page.php
> +     *     name="monsieurbiz_cms_page_channels",
Why ? I prefer to have `monsieurbiz` on the table name instead of `mbiz`

2020-11-10 10:46 UTC, jacquesbh commented on src/Entity/Page.php
> +     *     name="monsieurbiz_cms_page_channels",
Ok, then an `UPGRADE-1.0.md` is welcomed!

2020-11-10 12:19 UTC, maximehuran commented on src/Entity/Page.php
> +     *     name="monsieurbiz_cms_page_channels",
Done

2020-11-10 13:40 UTC, jacquesbh approved these changes

2020-11-10 13:40 UTC, jacquesbh commented
Big one!

Thank you Maxime 🎉.

We'll still have to tag when the Rich Editor v2 is out!

2020-11-10 13:40 UTC, merged