Allows 2 pages to have the same slug depending on channel and locale
monsieurbiz/SyliusCmsPagePlugin pull request #55
Opened 2023-09-07 08:26 UTC by delyriand

The PR allows you to create pages with the same slug for different channels and locales.

Example, for my "Fashion" channel: 

![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/7e146f14-1601-4b7e-b404-2bd051cfc8a0)

![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/098fcfd4-0a82-4bf0-9e71-00fbf209461f)

And another page with same slug for my "Test" channel:

![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/b9a3ac8a-b02f-4732-8316-665c12e35d87)

![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/19b7d028-1c66-426b-97d6-544295f6fba5)

If I try to save my second page with the "Fashion" channel:
![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/d4127b57-9b64-4d72-bc27-df6ff328beed)

Or create a new page with same "context":
![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/0aaf62a1-28da-439f-9e69-3c75e30988e4)

Add channel column and filter in page grid:
![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/465524/bded0d81-b893-4a1e-a60c-b64848f13430)

2023-09-07 08:31 UTC, etienne-monsieurbiz approved these changes
<!-- Praises highlight something positive. Try to leave at least one of these comments per review (if it exists :^)  -->
**👏 praise:** ‏ Amazing!

2023-09-08 09:40 UTC, maximehuran requested changes

2023-09-08 09:40 UTC, maximehuran commented on src/Resources/translations/validators.fr.yaml
> +            unique: 'Ce slug est déjà utilisé pour une autre page.'
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** ‏Improve translation

2023-09-08 10:11 UTC, maximehuran approved these changes

2023-09-08 10:11 UTC, merged